version: '3.1'

services:

  node:
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/var/www/kinobox
    links:
      - postgres
    command: npm run start:debug

  postgres:
    image: postgres:12
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
